// src/components/solid/App.tsx
import { Route, Router } from "@solidjs/router";
import { ColorModeProvider } from "@kobalte/core";
import type { CommunityData } from "@/utils/sdk";
import { DevelopmentPlaceholder } from "./components/DevelopmentPlaceholder";
import { GlobalContextProvider } from "./contexts/GlobalContext";
import AppLayout from "./layouts/AppLayout";
import CommunityLayout from "./layouts/CommunityLayout";
import ChannelView from "./views/ChannelView";
import { Toaster } from "./shadcn-solid/Sonner";

/**
 * The entrypoint to the main solid app.
 */
export const App = ({
	communities,
	user,
}: {
	communities: Array<CommunityData>;
	user: App.SessionData["user"];
}) => {
	return (
		<ColorModeProvider>
			<Toaster richColors position="bottom-right" />
			<GlobalContextProvider
				contextData={{
					communities,
					user,
				}}
			>
				<Router base="/app">
					<Route component={AppLayout}>
						<Route path="/" component={() => <DevelopmentPlaceholder />} />
						<Route component={CommunityLayout}>
							<Route
								path="/c/:community"
								component={() => <div>Community page</div>}
							/>
							<Route path="/c/:community/:channel" component={ChannelView} />
						</Route>
					</Route>
				</Router>
			</GlobalContextProvider>
		</ColorModeProvider>
	);
};

// packages/client/src/app.tsx
import { ParentComponent, Suspense } from "solid-js";
import { AppLoadingScreen } from "./components/AppLoadingScreen";
import { UserContextProvider } from "./contexts/User";
import { ColorModeProvider } from "@kobalte/core";
import { Toaster } from "./components/ui/Sonner";
import { Route, Router } from "@solidjs/router";
import AppLayout from "./layouts/AppLayout";
import { WelcomeScreen } from "./components/WelcomeScreen";

const App: ParentComponent = () => {
	return (
		<UserContextProvider>
			<ColorModeProvider>
				<Toaster richColors position="bottom-right" />

				<Router base="/app">
					<Route component={AppLayout}>
						<Route path="/" component={WelcomeScreen} />
						{/*<Route component={CommunityLayout}>
								<Route
									path="/c/:community"
									component={() => (
										<div class="w-full h-full flex items-center justify-center">
											TODO(app): Make this a page people can configure?
											Select a channel to get started!
										</div>
									)}
								/>
								<Route
									path="/c/:community/t/:channel"
									component={ChannelView}
								/>
								<Route
									path="/c/:community/v/:channel"
									component={VoiceChannelView}
								/>
							</Route>*/}
					</Route>
				</Router>
			</ColorModeProvider>
		</UserContextProvider>
	);
};

export default App;
